# Generated by Django 5.2.8 on 2025-12-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolaMundo', '0002_author_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='english_level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2, verbose_name='Nivel de Inglés'),
        ),
    ]
